#define LEFT_SOLENOID_PIN 17
#define RIGHT_SOLENOID_PIN 18

#define LIFT_ENABLE_PIN 11
#define LIFT_DIRECTION_PIN 9
#define LIFT_STEP_PIN 19
#define LIFT_HOMING_PIN 5

#define CANDY_1_ENABLE_PIN 20
#define CANDY_1_DIRECTION_PIN 10
#define CANDY_1_STEP_PIN 12

#define CANDY_2_ENABLE_PIN 4
#define CANDY_2_DIRECTION_PIN 3
#define CANDY_2_STEP_PIN 2

#define CANDY_3_ENABLE_PIN 21
#define CANDY_3_DIRECTION_PIN 22
#define CANDY_3_STEP_PIN 23

#define SODA_BUTTON_1_PIN 6
#define SODA_BUTTON_2_PIN 14
#define CANDY_BUTTON_1_PIN 13
#define CANDY_BUTTON_2_PIN 15
#define CANDY_BUTTON_3_PIN 16