#define LEFT_SOLENOID_PIN 0
#define RIGHT_SOLENOID_PIN 0

#define LIFT_ENABLE_PIN 0
#define LIFT_DIRECTION_PIN 0
#define LIFT_STEP_PIN 0
#define LIFT_HOMING_PIN 0

#define CANDY_1_ENABLE_PIN 0
#define CANDY_1_DIRECTION_PIN 0
#define CANDY_1_STEP_PIN 0

#define CANDY_2_ENABLE_PIN 0
#define CANDY_2_DIRECTION_PIN 0
#define CANDY_2_STEP_PIN 0

#define CANDY_3_ENABLE_PIN 0
#define CANDY_3_DIRECTION_PIN 0
#define CANDY_3_STEP_PIN 0

#define SODA_BUTTON_1_PIN 0
#define SODA_BUTTON_2_PIN 0
#define CANDY_BUTTON_1_PIN 0
#define CANDY_BUTTON_2_PIN 0
#define CANDY_BUTTON_3_PIN 0